#!/bin/bash

if [ ! -f ~/.forever/pids/twitterpub.pid ]; then 
  mkdir -p logs
  rm -f logs/*
  forever start --uid "twitterpub"  -p . -a -l logs/forever.log -o logs/out.log -e logs/err.log -c coffee --watch app.coffee start
fi
